name: Front-End CI

on:
  push:
    branches: [main, develop]
    paths:
      - "Front-End/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "Front-End/**"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front-End

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello World from Front-End CI"
